#!/usr/bin/env php
<?php
\chdir(__DIR__);
(function() {
    require_once 'vendor/autoload.php';
    $httpApplication = new \Ixocreate\ApplicationConsole\ConsoleApplication("bootstrap");
    $httpApplication->run();
})();
