<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="application-name" content="<?= $this->app('title') ?>"/>
  <title><?= $this->app('title') ?></title>
  <meta name="description" content="<?= $this->app('title') ?>">
  <link rel="stylesheet" href="https://ixocreate.github.io/current/css/vendor.min.css">
  <link rel="stylesheet" href="https://ixocreate.github.io/current/css/main.min.css">
  <link href="https://ixocreate.github.io/current/img/brand/ixocreate/favicon/favicon-128.png" rel="shortcut icon">
</head>
<body>
<div class="d-flex flex-column justify-content-center align-items-center text-center vh-100">
    <?= $this->section('content') ?>
</div>
</body>
</html>
